### ISSUE TITLE
Installation has failed with exit code 1 - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired

### ISSUE THREAD

**Issue by Jan-Petter1** [espressif/idf-installer#68] opened 2021-09-30 08:16 UTC
Hi
Trying to install esp_idf_tools the installer report this error:
Installation has failed with exit code 1
Jan-Petter Bakke

**Comment by georgik** [comment] 2021-09-30 08:30
@Jan-Petter1 Thank you for reporting the issue. To diagnose the problem we need more information.

Please, use the latest installer https://github.com/espressif/idf-installer/releases/tag/online-2.12-beta-01
If the installation fails, please attach the installation log.
You can access it in your home directory under \AppData\Temp\Setup*.txt or simply by clicking Full log button on the second screen.

**Comment by ingcicala** [comment] 2021-09-30 08:49
I have same problem!!!

exitcode 1 : 
"
  WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
                          WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\ESP_Tool\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          Downloading ninja-1.10.2-win64.zip to C:\ESP_Tool\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
                          WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\ESP_Tool\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          Downloading ninja-1.10.2-win64.zip to C:\ESP_Tool\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
                          WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\ESP_Tool\.espressif\dist\ninja-1.10.2-win64.zip.tmp
                          ERROR: Failed to download, and retry count has expired
                          Traceback (most recent call last):
                            File "C:\ESP_IDF\\tools\idf_tools.py", line 1675, in <module>
                              main(sys.argv[1:])
                            File "C:\ESP_IDF\\tools\idf_tools.py", line 1671, in main
                              action_func(args)
                            File "C:\ESP_IDF\\tools\idf_tools.py", line 1322, in action_install
                              tool_obj.download(tool_version)
                            File "C:\ESP_IDF\\tools\idf_tools.py", line 705, in download
                              raise DownloadError()
                          __main__.DownloadError
"
[Setup Log 2021-09-30 #003.txt](https://github.com/espressif/idf-installer/files/7258131/Setup.Log.2021-09-30.003.txt)

**Comment by ingcicala** [comment] 2021-09-30 08:50
[SSL: CERTIFICATE_VERIFY_FAILED]  ?????

**Comment by Jan-Petter1** [comment] 2021-09-30 08:51
Still the same problem

**Comment by georgik** [comment] 2021-09-30 09:08
@Jan-Petter1 Please try verify whether you can download this URL directly in your web browser:
https://dl.espressif.com/dl/ninja-1.10.2-win64.zip

If yes, please retry the installation. The certificate cache should be refreshed by the download from browser.

**Comment by ingcicala** [comment] 2021-09-30 09:08
Offline installer tools works ....

**Comment by Jan-Petter1** [comment] 2021-09-30 09:13
No difference

**Comment by ingcicala** [comment] 2021-09-30 09:13
offline installer tool works but it doesn't install eclipse .....
I will retry online tool ...

**Comment by ingcicala** [comment] 2021-09-30 09:15
Idem
No difference ......


> @Jan-Petter1 Please try verify whether you can download this URL directly in your web browser: https://dl.espressif.com/dl/ninja-1.10.2-win64.zip
> 
> If yes, please retry the installation. The certificate cache should be refreshed by the download from browser.

**Comment by georgik** [comment] 2021-09-30 09:22
@ingcicala Thank you for verification. That's an interesting issue.

Please try previous version of installer 2.10 which contains PowerShell code which refreshes Windows certificates, the method was changed in 2.11.
https://github.com/espressif/idf-installer/releases/tag/offline-2.10

Please, attach the install log, so that we can diagnose the problem.

**Comment by ingcicala** [comment] 2021-09-30 09:23
> offline installer tool works but it doesn't install eclipse ..... I will retry online tool ...

![image](https://user-images.githubusercontent.com/62546009/135425797-0e1b2b56-102e-4ecc-8df1-03d8e9aa46bf.png)

**Comment by ingcicala** [comment] 2021-09-30 09:43
online version 2.10 has the same problem
offline version 2.11 works but at the end it doesn't install eclipse ....

finally offline versione 2.10 works !!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ingcicala** [comment] 2021-09-30 10:10
eclipse in offline 2.10 doen't recognise IDF_PATH ..... uff

**Comment by Jan-Petter1** [comment] 2021-09-30 10:41
Thanks, it worked

**Comment by georgik** [comment] 2021-09-30 12:22
@ingcicala Thank you for posting details about 2.11 Offline problem with Eclipse deployment. I've created new issue to track this problem #69 

@Jan-Petter1 Thank you for confirmation that solution worked for you.

@ingcicala Regarding SSL: CERTIFICATE_VERIFY_FAILED on your Windows. Do you have some Windows Group Policy restrictions installed (often case in corporate notebooks) or different antivirus than Windows Defender?

I will also double check Python cryptography which seems to cause some troubles in the version released yesterday.

**Comment by georgik** [comment] 2021-10-01 07:33
If anybody else experience this issue, please add it to the comment. Please, provide Windows version (command winver), Windows Edition (home, enterprise, pro) and type of antivirus software (e.g. Windows Defender).

**Comment by georgik** [comment] 2021-10-04 06:56
The problem seems to be caused by outdated root certificates in the system: https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/?guccounter=1

**Comment by georgik** [comment] 2021-10-19 11:23
File server dl.espressif.com was moved to cloud storage with different certificate provider.
Closing the issue.

Feel free to reopen. In case of reopen please attach the log from the installer.

**Closed by georgik** 2021-10-19 11:23 UTC

**Comment by xiaolongba** [comment] 2021-11-01 14:26
@georgik it seems that I also encountered this issue, this is not the specific case, it should be the same as others, the details as below:
![CEOVJSUSHKTYRRH EW5XD9V](https://user-images.githubusercontent.com/16135532/139687239-937fcce3-030a-4e6c-84b0-58555c08ccfe.png)

the only workaround is to return back to https://github.com/espressif/idf-installer/releases/tag/offline-2.10 and then install the tools and then you can use the latest version https://github.com/espressif/idf-installer/releases/tag/online-2.12-beta-07 at this moment.
